language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: supersnager@gmail.com
  api_key:
    secure: 0NgC4o1BsaNIMKc8qs8hrRawR62qxdddFWIwZgsumRQBOcKfNfmcWTsWPO2ICJXsvlch6YtoM//PwCp8fVY9N88ybbIBYk6W2U6ebKa53HYPFvuolVbzeDsjjIWG3t/BvdMKfl8+IDcwMTtw0YbYwtyOpP2R9iaSTUNU7/KqsMHsNruNPEhsPknaWpEETsJXvB08jZ/litv9Sx8BxynXfN2rrFAO2RDQEtBpO5XBHwPzPX/+3astZuF1EA/fOn0955mUH5SMKJdPXJ4GApYwOVkICpazMZrJNOYzVgPJ3ZgCpfsKlQtOXAjkGeDPXOaNXjn4ehrU1jJqMHuTSwZgFJaz+eNXm2bVZFkRsrXFLvHD3emheRcJ7FFO0PtywHukyB6jqYdhGqG98Xz+2Bf3geMMLJKIdR/rASw6RRAFWTfQuGGdVuaR+mev+sL/qFBq9igKfEsTAPzOYytYMIeDvTGSAO6rpMNTRGBNUTuIzIYFlITeTiAhjDL3ZdlC6fmbEZHXH9uXLK+ZcetGmNR0LUdFJmIhE9CIXEWY90OPKMcsNt+q3dMxdNOHNRt+qNnCf3KuK38Yafd6LVPPiPqUgBV9DMQRWu0rCOupAj5QfuMRpUCrgL+ESX8IfIqBEHYH+12uWvJ+Omo8VUO8rlfz8dt3Kxw7IZOwEfetljnyi/8=
  skip_cleanup: true
  on:
    tags: true
    branch: master
